### ISSUE TITLE
Optimize Dashboard to resolve faster integration times 

### ISSUE THREAD

**Issue by steigersg** [MazinLab/MKIDReadout#58]
so we can better see things like speckle patterns in real time

**Comment by neelay893** [comment]
![image](https://user-images.githubusercontent.com/19984104/64653019-247cca00-d3da-11e9-8384-b6b114feea7a.png)

This is the weird error we got when dashboard crashed, after running at 0.1 s for a few min

**Comment by neelay893** [comment]
Jeb and I figured this was b/c convertImage is too slow to support these int times, for now just run at >0.5 s or so
