### ISSUE TITLE
Threading error in dashboard

### ISSUE THREAD

**Issue by nswimmer** [MazinLab/MKIDReadout#64]
After dashboard has been running for a long time with the black fridge, an error comes up where a new thread cannot be started. See traceback below

![image](https://user-images.githubusercontent.com/31903948/67155127-d783f180-f2bd-11e9-97aa-d7a7940cae5d.png)

**Comment by nswimmer** [comment]
When this error appears, data is still being taken and written to the data directory, I think the problem it has is with the number of threads it has made from creating FITS files. Not sure if this is because this is the first time we've taken data for this long and so it hasn't been a problem before, but it doesn't seem to be messing up the data itself.

**Comment by baileyji** [comment]
I've done some work here. Time to test it again.
